[project]
name = "soulecho"
version = "0.1.0"
description = "个人日志疗愈Agent"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.5.9",
    "fastapi>=0.141.1",
    "langchain>=1.4.2",
    "langchain-openai>=1.6.2",
    "langchain-typesafe>=0.0.1a3",
    "langgraph>=1.2.11",
    "loguru>=0.7.3",
    "mem0ai>=2.1.0",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.53.0",
]
